/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsQuestionsRouteImport } from './routes/tests.questions'
import { Route as TestsPublishRouteImport } from './routes/tests.publish'
import { Route as TestsCreateRouteImport } from './routes/tests.create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsQuestionsRoute = TestsQuestionsRouteImport.update({
  id: '/tests/questions',
  path: '/tests/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsPublishRoute = TestsPublishRouteImport.update({
  id: '/tests/publish',
  path: '/tests/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsCreateRoute = TestsCreateRouteImport.update({
  id: '/tests/create',
  path: '/tests/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tests/create': typeof TestsCreateRoute
  '/tests/publish': typeof TestsPublishRoute
  '/tests/questions': typeof TestsQuestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tests/create': typeof TestsCreateRoute
  '/tests/publish': typeof TestsPublishRoute
  '/tests/questions': typeof TestsQuestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tests/create': typeof TestsCreateRoute
  '/tests/publish': typeof TestsPublishRoute
  '/tests/questions': typeof TestsQuestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/tests/create' | '/tests/publish' | '/tests/questions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/tests/create' | '/tests/publish' | '/tests/questions'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/tests/create'
    | '/tests/publish'
    | '/tests/questions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TestsCreateRoute: typeof TestsCreateRoute
  TestsPublishRoute: typeof TestsPublishRoute
  TestsQuestionsRoute: typeof TestsQuestionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/questions': {
      id: '/tests/questions'
      path: '/tests/questions'
      fullPath: '/tests/questions'
      preLoaderRoute: typeof TestsQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/publish': {
      id: '/tests/publish'
      path: '/tests/publish'
      fullPath: '/tests/publish'
      preLoaderRoute: typeof TestsPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/create': {
      id: '/tests/create'
      path: '/tests/create'
      fullPath: '/tests/create'
      preLoaderRoute: typeof TestsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TestsCreateRoute: TestsCreateRoute,
  TestsPublishRoute: TestsPublishRoute,
  TestsQuestionsRoute: TestsQuestionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
